name: CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

jobs:
  test:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js latest
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm i

      - name: Run Tests
        run: npm run test:cov

      - name: Run Prettier
        run: npm run prettier

      - name: Run Linter
        run: npm run lint:fix
